- name: User Creation
  hosts: dev,test
  vars_files: 
      - ~/ansible/user_list.yaml
      - ~/ansible/vault.yaml
  tasks:
    - name: Creating devops group
      group:
         name: devops
         state: present
    - name: Creating adam user
      user: 
         name: '{{ item.name }}'
         uid: '{{ item.uid }}'
         groups: devops
         password: "{{ dev_pass | password_hash('sha512') }}"
      when: item.job == "developer"
      loop: '{{ users }}'
- hosts: prod
  vars_files: 
      - ~/ansible/user_list.yaml
      - ~/ansible/vault.yaml
  tasks:
    - name: Creating opsmgr group
      group:
         name: opsmgr
         state: present
    - name: Creating gabriel user
      user: 
         name: '{{ item.name }}'
         uid: '{{ item.uid }}'
         groups: opsmgr
         password: "{{ mgr_pass | password_hash('sha512') }}"
      when: item.job == "manager"
      loop: '{{ users }}'

