- name: Hardware report Playbook
  hosts: all
  tasks:
#    - name: Downloadning the file from a given link
 #     get_url:
  #      url: https://example.classroom.com
   #     dest: /root/hwreport.txt
    - name: Set hostname value
      lineinfile:
        path: /root/hwreport.txt
        regexp: '^Hostname'
        line: Hostname: {{ ansible_hostname | default('NONE') }}
    - name: Set biosversion value
      lineinfile:
        path: /root/hwreport.txt
        regexp: '^Biosversion'
        line: Biosversion: {{ ansible_bios_version | default('NONE') }}
    - name: Set memory value
      lineinfile:
        path: /root/hwreport.txt
        regexp: '^Memory'
        line: Memory: {{ ansible_memtotal_mb | default('NONE') }}
    - name: Set vda value
      lineinfile:
        path: /root/hwreport.txt
        regexp: '^Vda'
        line: vda: {{ ansible_devices.nvme0n1.partitions.nvme0n1p4.size | default('NONE') }}
    - name: Set vdb value
      lineinfile:
        path: /root/hwreport.txt
        regexp: '^Vdb'
        line: vdb: {{ ansible_devices.nvme0n1.partitions.nvme0n1p3.size | default('NONE') }}
